# service-repos/auth_api/helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  labels:
    app: auth-api
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
    - port: 5000
      targetPort: 5000