name: Build and Deploy

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-and-deploy:
    uses: KominskyOrg/kom_reusable_workflows/.github/workflows/eks_deployment.yml@v1.2
    secrets: inherit